create table if not exists public.config (
    config_key text primary key,
    guidance jsonb not null default '{}'::jsonb
);

create table if not exists public.albums (
    album_uuid uuid primary key,
    album_title text,
    album_year integer,
    album_category text,
    album_music_director text,
    album_lyricist text,
    album_label text,
    album_rating numeric
);

create table if not exists public.songs (
    song_uuid uuid primary key,
    album_uuid uuid references public.albums(album_uuid),
    track_number integer,
    song_title text,
    song_singers text,
    song_rating numeric,
    youtube_url text,
    music_yt_url_1 text,
    music_yt_url_2 text,
    music_yt_url_3 text,
    youtube_video_id text,
    is_used boolean not null default false,
    used_at timestamptz,
    used_playlist_title text,
    used_playlist_id text,
    last_validated_at timestamptz,
    is_youtube_live boolean,
    validation_status text
);

create extension if not exists pg_trgm;

create index if not exists songs_album_uuid_idx
    on public.songs (album_uuid);

create index if not exists songs_is_used_idx
    on public.songs (is_used);

create index if not exists songs_unused_with_youtube_idx
    on public.songs (song_uuid)
    where is_used = false and youtube_url is not null and youtube_url <> '';

create index if not exists songs_youtube_video_id_idx
    on public.songs (youtube_video_id);

create index if not exists songs_song_rating_idx
    on public.songs (song_rating);

create index if not exists songs_song_singers_trgm_idx
    on public.songs using gin (song_singers gin_trgm_ops);

create index if not exists albums_album_year_idx
    on public.albums (album_year);

create index if not exists albums_album_rating_idx
    on public.albums (album_rating);

create index if not exists albums_music_director_trgm_idx
    on public.albums using gin (album_music_director gin_trgm_ops);

create index if not exists albums_year_rating_idx
    on public.albums (album_year, album_rating);

create table if not exists public.listener_profiles (
    profile_id text primary key,
    listener_name text not null,
    playlist_prefix text not null,
    songs_per_week integer not null,
    include_queries jsonb not null,
    exclude_keywords jsonb not null,
    preferred_artists jsonb not null,
    preferred_eras jsonb not null,
    preferred_moods jsonb not null,
    language_hint text not null,
    country_code text not null,
    playlist_description text not null,
    use_llm boolean not null default false,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.curated_videos (
    video_id text primary key,
    title text not null,
    channel_title text not null,
    inferred_artist text,
    inferred_era text,
    query text not null,
    playlist_title text not null,
    curated_at timestamptz not null,
    song_uuid uuid references public.songs(song_uuid),
    album_uuid uuid references public.albums(album_uuid),
    youtube_url text,
    source text not null default 'youtube_search'
);

alter table public.curated_videos
    add column if not exists song_uuid uuid references public.songs(song_uuid);

alter table public.curated_videos
    add column if not exists album_uuid uuid references public.albums(album_uuid);

alter table public.curated_videos
    add column if not exists youtube_url text;

alter table public.curated_videos
    add column if not exists source text not null default 'youtube_search';

create table if not exists public.curation_runs (
    id bigint generated by default as identity primary key,
    playlist_title text not null,
    curated_at timestamptz not null,
    total_candidates integer not null,
    selected_count integer not null
);

create index if not exists curated_videos_curated_at_idx
    on public.curated_videos (curated_at desc);

create index if not exists curated_videos_artist_idx
    on public.curated_videos (inferred_artist);

create index if not exists curated_videos_era_idx
    on public.curated_videos (inferred_era);

create index if not exists curated_videos_playlist_source_idx
    on public.curated_videos (playlist_title, source);

create index if not exists curated_videos_song_uuid_idx
    on public.curated_videos (song_uuid);

create index if not exists curated_videos_album_uuid_idx
    on public.curated_videos (album_uuid);

create index if not exists curated_videos_source_idx
    on public.curated_videos (source);

create index if not exists curation_runs_playlist_title_idx
    on public.curation_runs (playlist_title);
