create table if not exists public.config (
    config_key text primary key,
    guidance jsonb not null default '{}'::jsonb
);

create table if not exists public.listener_profiles (
    profile_id text primary key,
    listener_name text not null,
    playlist_prefix text not null,
    songs_per_week integer not null,
    include_queries jsonb not null,
    exclude_keywords jsonb not null,
    preferred_artists jsonb not null,
    preferred_eras jsonb not null,
    preferred_moods jsonb not null,
    language_hint text not null,
    country_code text not null,
    playlist_description text not null,
    use_llm boolean not null default false,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.curated_videos (
    video_id text primary key,
    title text not null,
    channel_title text not null,
    inferred_artist text,
    inferred_era text,
    query text not null,
    playlist_title text not null,
    curated_at timestamptz not null
);

create table if not exists public.curation_runs (
    id bigint generated by default as identity primary key,
    playlist_title text not null,
    curated_at timestamptz not null,
    total_candidates integer not null,
    selected_count integer not null
);

create index if not exists curated_videos_curated_at_idx
    on public.curated_videos (curated_at desc);

create index if not exists curated_videos_artist_idx
    on public.curated_videos (inferred_artist);

create index if not exists curated_videos_era_idx
    on public.curated_videos (inferred_era);
